# Generated by Django 5.2.8 on 2026-05-17 08:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKPreference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
                model_name='eventparticipant',
                name='uuid',
                field=models.UUIDField(default=uuid.uuid4,
                                       help_text='Unique and non-guessable identifier for this participant', null=True,
                                       verbose_name='UUID'),
        ),
    ]
