# Generated by Django 5.2.8 on 2026-05-17 08:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKPreference', '0003_participant_uuid_populate'),
    ]

    operations = [
        migrations.AlterField(
                model_name='eventparticipant',
                name='uuid',
                field=models.UUIDField(default=uuid.uuid4,
                                       help_text='Unique and non-guessable identifier for this participant',
                                       unique=True, verbose_name='UUID'),
        ),
    ]
