# Generated by Django 2.2.6 on 2019-10-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0001_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AKOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name used to identify an AK owner', max_length=256, verbose_name='Nickname')),
                ('email', models.EmailField(blank=True, help_text='Contact e-mail', max_length=128, verbose_name='E-Mail Address')),
                ('institution', models.CharField(blank=True, help_text='University etc.', max_length=128, verbose_name='Institution')),
                ('link', models.URLField(blank=True, help_text='Link to Homepage', verbose_name='Web Link')),
                ('event', models.ForeignKey(help_text='Matching event', on_delete=django.db.models.deletion.CASCADE, to='AKModel.Event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'AK Owner',
                'verbose_name_plural': 'AK Owners',
                'ordering': ['name'],
                'unique_together': {('name', 'institution')},
            },
        ),
    ]
