# Generated by Django 2.2.6 on 2019-10-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0003_ak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or number of the room', max_length=64, verbose_name='Name')),
                ('building', models.CharField(help_text='Name or number of the building', max_length=256, verbose_name='Building')),
                ('capacity', models.IntegerField(help_text='Maximum number of people', verbose_name='Capacity')),
                ('event', models.ForeignKey(help_text='Matching event', on_delete=django.db.models.deletion.CASCADE, to='AKModel.Event', verbose_name='Event')),
                ('properties', models.ManyToManyField(help_text='AK requirements fulfilled by the room', to='AKModel.AKRequirement', verbose_name='Properties')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['building', 'name'],
                'unique_together': {('name', 'building')},
            },
        ),
    ]
