# Generated by Django 2.2.6 on 2019-10-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0004_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='AKSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Time and date the slot begins', verbose_name='Slot Begin')),
                ('duration', models.DecimalField(decimal_places=2, default=2, help_text='Length in hours', max_digits=4, verbose_name='Duration')),
                ('ak', models.ForeignKey(help_text='AK being mapped', on_delete=django.db.models.deletion.CASCADE, to='AKModel.AK', verbose_name='AK')),
                ('event', models.ForeignKey(help_text='Matching event', on_delete=django.db.models.deletion.CASCADE, to='AKModel.Event', verbose_name='Event')),
                ('room', models.ForeignKey(help_text='Room the AK will take place in', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AKModel.Room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'AK Slot',
                'verbose_name_plural': 'AK Slots',
                'ordering': ['start', 'room'],
            },
        ),
    ]
