# Generated by Django 2.2.6 on 2019-10-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0006_translation_akmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('ak', models.ForeignKey(blank=True, help_text='AK whose availability this is', null=True,
                                         on_delete=django.db.models.deletion.CASCADE, related_name='availabilities',
                                         to='AKModel.AK', verbose_name='AK')),
                ('ak_type', models.ForeignKey(blank=True, help_text='AK Type whose availability this is', null=True,
                                              on_delete=django.db.models.deletion.CASCADE,
                                              related_name='availabilities', to='AKModel.AKType',
                                              verbose_name='AK Type')),
                ('event', models.ForeignKey(help_text='Associated event', on_delete=django.db.models.deletion.CASCADE,
                                            related_name='availabilities', to='AKModel.Event', verbose_name='Event')),
                ('person', models.ForeignKey(blank=True, help_text='Person whose availability this is', null=True,
                                             on_delete=django.db.models.deletion.CASCADE, related_name='availabilities',
                                             to='AKModel.AKOwner', verbose_name='Person')),
                ('room', models.ForeignKey(blank=True, help_text='Room whose availability this is', null=True,
                                           on_delete=django.db.models.deletion.CASCADE, related_name='availabilities',
                                           to='AKModel.Room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'ordering': ['event', 'start'],
            },
        ),
    ]
