# Generated by Django 2.2.6 on 2019-10-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0007_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ak',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Track the AK belongs to', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='AKModel.AKTrack',
                                    verbose_name='Track'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, help_text='City etc. the event takes place in', max_length=128,
                                   verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, help_text='Name or number of the building', max_length=256,
                                   verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='properties',
            field=models.ManyToManyField(blank=True, help_text='AK requirements fulfilled by the room',
                                         to='AKModel.AKRequirement', verbose_name='Properties'),
        ),
    ]
