# Generated by Django 2.2.6 on 2019-10-16 18:41

from django.db import migrations


def gen_slug(apps, schema_editor):
    event = apps.get_model('AKModel', 'Event')
    for row in event.objects.all():
        row.slug = ''.join(filter(str.isalnum, row.name.lower()))
        row.save(update_fields=['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0009_add_event_slug_field'),
    ]

    operations = [
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop)
    ]
