# Generated by Django 2.2.6 on 2019-10-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0012_ak_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ak',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='ak_type',
            field=models.IntegerField(),
        ),
        migrations.RenameModel(
            old_name='AKType',
            new_name='AKCategory',
        ),
        migrations.RenameField(
            model_name='ak',
            old_name='type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='ak_type',
            new_name='ak_category',
        ),
        migrations.AlterField(
            model_name='ak',
            name='category',
            field=models.ForeignKey(help_text='Category of the AK', on_delete=django.db.models.deletion.PROTECT,
                                    to='AKModel.AKCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='ak_category',
            field=models.ForeignKey(blank=True, help_text='AK Category whose availability this is', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='availabilities',
                                    to='AKModel.AKCategory', verbose_name='AK Category'),
        ),
    ]
