# Generated by Django 2.2.6 on 2019-10-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0013_aktype_to_akcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akcategory',
            options={'ordering': ['name'], 'verbose_name': 'AK Category', 'verbose_name_plural': 'AK Categories'},
        ),
        migrations.AlterField(
            model_name='akcategory',
            name='name',
            field=models.CharField(help_text='Name of the AK Category', max_length=64, unique=True,
                                   verbose_name='Name'),
        ),
    ]
