# Generated by Django 2.2.6 on 2019-10-18 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0015_ak_present_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akslot',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room the AK will take place in', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='AKModel.Room',
                                    verbose_name='Room'),
        ),
    ]
