# Generated by Django 2.2.6 on 2019-10-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0016_category_description'),
        ('AKModel', '0017_owner_slug'),
    ]

    operations = [
    ]
