# Generated by Django 2.2.6 on 2019-10-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0025_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='akslot',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
    ]
