# Generated by Django 2.2.6 on 2020-05-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0028_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ak',
            name='notes',
            field=models.TextField(blank=True,
                                   help_text='Notes to organizers. These are public. For private notes, please send an e-mail.',
                                   verbose_name='Organizational Notes'),
        ),
    ]
