# Generated by Django 2.2.6 on 2020-05-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0029_AK_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ak',
            name='interest_counter',
            field=models.IntegerField(default=0, help_text='People who have indicated interest online',
                                      verbose_name='Interest Counter'),
        ),
    ]
