# Generated by Django 2.2.6 on 2020-05-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0030_AK_interest_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
