# Generated by Django 3.0.6 on 2020-05-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0033_AKOnline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['location', 'name'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, help_text='Name or number of the location', max_length=256,
                                   verbose_name='Location'),
        ),
    ]
