# Generated by Django 3.0.6 on 2020-05-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0034_room_rename_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='plan_hidden',
            field=models.BooleanField(default=True, help_text='Hides plan for non-staff users', verbose_name='Plan Hidden'),
        ),
    ]
