# Generated by Django 3.0.6 on 2020-11-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0041_constraint_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='akslot',
            name='fixed',
            field=models.BooleanField(default=False, help_text='Length and time of this AK should not be changed', verbose_name='Scheduling Fixed'),
        ),
    ]
