# Generated by Django 3.1.5 on 2021-01-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0043_akslot_fixed_improve_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalak',
            name='interest_counter',
        ),
    ]
