# Generated by Django 3.1.8 on 2021-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0046_present_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(help_text='Maximum number of people (-1 for unlimited).', verbose_name='Capacity'),
        ),
    ]
