# Generated by Django 3.1.8 on 2021-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0048_constraint_violation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interest_end',
            field=models.DateTimeField(blank=True, help_text='Closing time for expression of interest.', null=True,
                                       verbose_name='Interest Window End'),
        ),
        migrations.AddField(
            model_name='event',
            name='interest_start',
            field=models.DateTimeField(blank=True, help_text='Opening time for expression of interest.', null=True,
                                       verbose_name='Interest Window Start'),
        ),
    ]
