# Generated by Django 3.1.8 on 2022-08-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0050_message_event_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ak',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes to organizers. These are public. For private notes, please use the button for private messages on the detail page of this AK (after creation/editing).', verbose_name='Organizational Notes'),
        ),
        migrations.AlterField(
            model_name='historicalak',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes to organizers. These are public. For private notes, please use the button for private messages on the detail page of this AK (after creation/editing).', verbose_name='Organizational Notes'),
        ),
    ]
