# Generated by Django 3.2.16 on 2022-10-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0053_plan_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Time and date the slot begins', verbose_name='Slot Begin')),
                ('end', models.DateTimeField(help_text='Time and date the slot ends', verbose_name='Slot End')),
                ('event', models.ForeignKey(help_text='Associated event', on_delete=django.db.models.deletion.CASCADE, to='AKModel.event', verbose_name='Event')),
                ('primary_categories', models.ManyToManyField(blank=True, help_text='Categories that should be assigned to this slot primarily', to='AKModel.AKCategory', verbose_name='Primary categories')),
            ],
            options={
                'verbose_name': 'Default Slot',
                'verbose_name_plural': 'Default Slots',
                'ordering': ['-start'],
            },
        ),
    ]
