# Generated by Django 3.2.16 on 2023-01-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0055_ak_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ak',
            name='tags',
        ),
        migrations.DeleteModel(
            name='AKTag',
        ),
    ]
