# Generated by Django 4.1.5 on 2023-01-03 17:04

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0056_remove_tags'),
    ]

    operations = [
        migrations.AlterField(
                model_name='event',
                name='timezone',
                field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Europe/Berlin',
                                                          help_text='Time Zone where this event takes place in',
                                                          verbose_name='Time Zone'),
        ),
    ]
