# Generated by Django 4.1.9 on 2023-05-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0057_upgrades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ak',
            options={'ordering': ['pk'], 'verbose_name': 'AK', 'verbose_name_plural': 'AKs'},
        ),
    ]
