# Generated by Django 4.2.11 on 2024-04-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0058_alter_ak_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interest_start',
            field=models.DateTimeField(blank=True, help_text='Opening time for expression of interest. When left blank, no interest indication will be possible.', null=True, verbose_name='Interest Window Start'),
        ),
    ]
