# Generated by Django 4.2.11 on 2024-04-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0059_interest_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='akorgamessage',
            name='resolved',
            field=models.BooleanField(default=False, help_text='This message has been resolved (no further action needed)', verbose_name='Resolved'),
        ),
    ]
