# Generated by Django 4.2.13 on 2025-02-25 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0060_orga_message_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AKType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name describing the type', max_length=128, verbose_name='Name')),
                ('event', models.ForeignKey(help_text='Associated event', on_delete=django.db.models.deletion.CASCADE, to='AKModel.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'AK Type',
                'verbose_name_plural': 'AK Types',
                'ordering': ['name'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.AddField(
            model_name='ak',
            name='types',
            field=models.ManyToManyField(blank=True, help_text='This AK is', to='AKModel.aktype', verbose_name='Types'),
        ),
    ]
