# Generated by Django 4.2.13 on 2025-02-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0061_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalak',
            name='interest',
        ),
    ]
