# Generated by Django 5.1.6 on 2025-03-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AKModel", "0063_field_validators"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="export_slot",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Slot duration in hours that is used in the timeslot discretization, when this event is exported for the solver.",
                max_digits=4,
                verbose_name="Export Slot Length",
            ),
        ),
    ]
