# Generated by Django 4.2.13 on 2025-02-10 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AKModel", "0064_event_export_slot"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name to identify a participant by (in case of questions from the organizers)",
                        max_length=64,
                        verbose_name="Nickname",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        help_text="Uni etc.",
                        max_length=128,
                        verbose_name="Institution",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Associated event",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AKModel.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AKPreference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Ignore"),
                            (1, "Prefer"),
                            (2, "Strong prefer"),
                            (3, "Required"),
                        ],
                        default=0,
                        help_text="Preference level for the AK",
                        verbose_name="Preference",
                    ),
                ),
                (
                    "ak",
                    models.ForeignKey(
                        help_text="AK this preference belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AKModel.ak",
                        verbose_name="AK",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Associated event",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AKModel.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        help_text="Participant this preference belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AKModel.eventparticipant",
                        verbose_name="Participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AK Preference",
                "verbose_name_plural": "AK Preferences",
            },
        ),
        migrations.AddField(
            model_name="availability",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                help_text="Participant whose availability this is",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="AKModel.eventparticipant",
                verbose_name="Participant",
            ),
        ),
    ]
