# Generated by Django 4.2.13 on 2025-02-10 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AKModel", "0065_eventparticipant_akpreference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="akpreference",
            name="slot",
            field=models.ForeignKey(
                default=None,
                help_text="AKSlot this preference belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="AKModel.akslot",
                verbose_name="AKSlot",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="akpreference",
            unique_together={("event", "participant", "slot")},
        ),
        migrations.RemoveField(
            model_name="akpreference",
            name="ak",
        ),
    ]
