# Generated by Django 4.2.13 on 2025-02-11 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "AKModel",
            "0066_akpreference_slot_alter_akpreference_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="requirements",
            field=models.ManyToManyField(
                blank=True,
                help_text="Participant's Requirements",
                to="AKModel.akrequirement",
                verbose_name="Requirements",
            ),
        ),
        migrations.AlterField(
            model_name="akpreference",
            name="slot",
            field=models.ForeignKey(
                help_text="AK Slot this preference belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="AKModel.akslot",
                verbose_name="AK Slot",
            ),
        ),
    ]
