# Generated by Django 5.2.1 on 2025-06-17 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0067_eventparticipant_requirements_and_more'),
        ('AKPreference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='participant',
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
        migrations.AddField(
            model_name='availability',
            name='participant',
            field=models.ForeignKey(blank=True, help_text='Participant whose availability this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='AKPreference.eventparticipant', verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='event',
            name='poll_hidden',
            field=models.BooleanField(default=True, help_text='Hides preference poll for non-staff users', verbose_name='Poll Hidden'),
        ),
        migrations.AddField(
            model_name='event',
            name='poll_published_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp at which the preference poll was published', null=True, verbose_name='Poll published at'),
        ),
        migrations.DeleteModel(
            name='AKPreference',
        ),
    ]
