# Generated by Django 5.1.6 on 2025-04-04 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AKModel", "0067_eventparticipant_requirements_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="akpreference",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "AK Preference",
                "verbose_name_plural": "AK Preferences",
            },
        ),
        migrations.AddField(
            model_name="akpreference",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Time of creation",
                verbose_name="Timestamp",
            ),
            preserve_default=False,
        ),
    ]
