# Generated by Django 5.1.6 on 2025-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AKModel", "0068_alter_akpreference_options_akpreference_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="akpreference",
            name="preference",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Ignore"),
                    (1, "Interested"),
                    (2, "Great interest"),
                    (3, "Required"),
                ],
                default=0,
                help_text="Preference level for the AK",
                verbose_name="Preference",
            ),
        ),
    ]
