# Generated by Django 5.2.1 on 2025-06-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0068_aktype_slug'),
        ('AKModel', '0068_event_export_delete_preferences_participants'),
    ]

    operations = [
    ]
