# Generated by Django 5.1.6 on 2025-04-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AKModel", "0069_alter_akpreference_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="poll_hidden",
            field=models.BooleanField(
                default=True,
                help_text="Hides preference poll for non-staff users",
                verbose_name="Poll Hidden",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="poll_published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp at which the preference poll was published",
                null=True,
                verbose_name="Poll published at",
            ),
        ),
    ]
