# Generated by Django 5.2.1 on 2025-06-13 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AKModel", "0070_event_poll_hidden_event_poll_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="akpreference",
            name="ak",
            field=models.ForeignKey(
                help_text="AK this preference belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AKModel.ak",
                verbose_name="AK",
            ),
        ),
    ]
