# Generated by Django 5.2.1 on 2025-06-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AKModel", "0070_event_poll_hidden_event_poll_published_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="akpreference",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="akpreference",
            name="event",
        ),
        migrations.RemoveField(
            model_name="akpreference",
            name="participant",
        ),
        migrations.RemoveField(
            model_name="akpreference",
            name="slot",
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="requirements",
        ),
    ]
