# Generated by Django 5.2.3 on 2025-06-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0070_requirements_relevant_for_participants'),
    ]

    operations = [
        migrations.AlterField(
                model_name='event',
                name='slug',
                field=models.SlugField(help_text='Short name of letters/numbers/dashes/underscores used in URLs.',
                                       max_length=32, unique=True, verbose_name='Short Form'),
        ),
    ]
