# Generated by Django 5.2.1 on 2025-06-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AKModel", "0071_alter_akpreference_unique_together_and_more"),
        ("AKPreference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                help_text="Participant whose availability this is",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="AKPreference.eventparticipant",
                verbose_name="Participant",
            ),
        ),
        migrations.DeleteModel(
            name="AKPreference",
        ),
        migrations.DeleteModel(
            name="EventParticipant",
        ),
    ]
