# Generated by Django 5.2.3 on 2025-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AKModel', '0071_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
                model_name='ak',
                name='goal',
                field=models.CharField(default='-',
                                       help_text='Design of the AK (e.g. discussion, problem solving, brainstorming, input, output) and/or goal (e.g. Reso, solution, collection of ideas, document, exchange) in a few words',
                                       max_length=512, verbose_name='Design/Goal'),
                preserve_default=False,
        ),
        migrations.AddField(
                model_name='ak',
                name='info',
                field=models.TextField(blank=True,
                                       help_text='Anything else about the AK, e.g. links, stories, detailed description',
                                       verbose_name='Further Information'),
        ),
        migrations.AddField(
                model_name='historicalak',
                name='goal',
                field=models.CharField(default='-',
                                       help_text='Design of the AK (e.g. discussion, problem solving, brainstorming, input, output) and/or goal (e.g. Reso, solution, collection of ideas, document, exchange) in a few words',
                                       max_length=512, verbose_name='Design/Goal'),
                preserve_default=False,
        ),
        migrations.AddField(
                model_name='historicalak',
                name='info',
                field=models.TextField(blank=True,
                                       help_text='Anything else about the AK, e.g. links, stories, detailed description',
                                       verbose_name='Further Information'),
        ),
        migrations.AlterField(
                model_name='ak',
                name='description',
                field=models.TextField(help_text='1-2 sentences of AK description', verbose_name='Brief Description'),
        ),
        migrations.AlterField(
                model_name='historicalak',
                name='description',
                field=models.TextField(help_text='1-2 sentences of AK description', verbose_name='Brief Description'),
        ),
    ]
