# Generated by Django 5.2.1 on 2025-06-13 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AKModel", "0072_akpreference_populate_ak"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="akpreference",
            unique_together={("event", "participant", "ak")},
        ),
        migrations.AlterField(
            model_name="akpreference",
            name="ak",
            field=models.ForeignKey(
                help_text="AK this preference belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="AKModel.ak",
                verbose_name="AK",
            ),
        ),
        migrations.RemoveField(
            model_name="akpreference",
            name="slot",
        ),
    ]
