# Generated by Django 5.2.3 on 2025-11-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AKModel', '0073_ak_prerequisites_reverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='ak',
            name='trashed_at',
            field=models.DateTimeField(help_text='If filled, AK was trashed at:', null=True, verbose_name='Trashed at'),
        ),
        migrations.AddField(
            model_name='historicalak',
            name='trashed_at',
            field=models.DateTimeField(help_text='If filled, AK was trashed at:', null=True, verbose_name='Trashed at'),
        ),
    ]
