# Generated by Django 3.2.16 on 2023-01-03 16:50

from django.db import migrations
import fontawesome_6.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AKDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardbutton',
            name='icon',
            field=fontawesome_6.fields.IconField(blank=True, default='external-link-alt', help_text='Symbol represeting this button.', max_length=60, verbose_name='Icon'),
        ),
    ]
