# Generated by Django 4.1.5 on 2023-03-21 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AKOnline', '0002_rework_virtual'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualRoom',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                              related_name='virtual', serialize=False, to='AKModel.room',
                                              verbose_name='Room')),
                ('url', models.URLField(blank=True, help_text='URL to the room or server', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Virtual Room',
                'verbose_name_plural': 'Virtual Rooms',
            },
        ),
    ]
