# Generated by Django 4.1.5 on 2023-03-21 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AKOnline', '0004_rework_virtual_3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualRoomOld',
        ),
    ]
